behaviors:
  configGoTarget:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    max_steps: 5000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
        smoothing: 0.99
